
networks:
  backnet:
  frontnet:

services:

  db:
    networks:
    - backnet

  backend_flask:
    build: backend_flask
    restart: always
    secrets:
      - db-password
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy

  proxy_flask:
    build: proxy_flask
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend_flask
    networks:
      - frontnet